# Generated by Django 5.2.8 on 2025-11-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
    ]
