# Generated by Django 5.2.8 on 2025-11-14 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0002_delete_profile"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                ),
                migrations.DeleteModel(
                    name="Address",
                ),
                migrations.DeleteModel(
                    name="Letting",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Letting",
                    table="letting_letting",
                ),
                migrations.AlterModelTable(
                    name="Address",
                    table="letting_address",
                ),
            ],
        ),
    ]
